export enum sagaActions {
  FETCH_GET_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER',
  FETCH_WEATHER_NEXT_FIVE_DAYS = 'FETCH_WEATHER_NEXT_FIVE_DAYS',
  FETCH_GET_CURRENT_DAY_WEATHER = 'FETCH_GET_CURRENT_DAY_WEATHER',
}
